function repititions = markRepititions(TrialList, lastT)
%% Find the repittive sequences (R-seq) and mark them as invalid

% There are two types of R-seqs: Long and Short.
%
% The long ones are the ones caused by either lack of motivation of the
% monkey to correctly complete an unrewarded trial or intentionally leaving
% a rewarded trial incomplete (after the reward is delivered but before the
% required time of fixation is reached) hence triggering the repitition of
% the same trial with the intention to redo the same trial and regain
% reward.
%
% As mentioned above, based on the length of the repititive sequence they
% are categorized into long and short. 

% 1. Long R-seq: Given that the long ones are easy to spot visually, their 
% identification was done by visual inspection. The outputs were recorded 
% in a text file named "lastTrial" stored together with the original MAT 
% data file in the same folder. They are labelled as "0" (zero) in the
% output variable dubbed "rSeq".

% 2. Short R-seq: They are defined as more than two repitition of any
% trial. This definition is based on the structure of the list of trials
% that doesn't permit more than two trials of the same kind (with the same
% positional index) to appear in a sequence back to back. They are labelled 
% by three values "1, 2, and 3" in the output variable, rSeq. Here, I
% explain how this has been done.

% This script deals with the recognition and lebelling of the short R-seqs.

% Imagine the following sequence of postion index 5 repiting 6 times:
%
% PositionIndex:  ...5 5 5 5 5 5...
%         Index:  ...1 2 3 4 5 6...
%
% This scripts labels the above the seqence as below:
%
% PositionIndex:  ...5 5 5 5 5 5...
%         Index:  ...1 2 3 4 5 6...
%          rSeq:  ...1 2 2 2 2 3...
%
% Where 1 indicate the beginning of the short R-seq, 2 invalidly repeated
% trials, and 3 the end of the sequence.

% Input arguments:
% 1. TrialList: TrialList(:,1) -> trialID; 
%               TrialList(:,41) -> rewardDuration;
%               TrialList(:,3) -> PositionIndex 
%                                 (Check out the end of this script for the
%                                 indices)
% 2. lastT: a set of indices marking the beginning and end of the trials
%           that are non-repititive on the macro scale. It was generated by
%           manually indpecting the data files.
%


% Output: repititions is a list with four different values:
%         0: non-repititive trials
%         1: the beginning a micro-repititive sequence
%         3: its end is marked by 3.
% 	      2: indicates the trials that are repititive and need to be
%            discarded.

%% find the micro-repititive sequences (mR-seq)
% On a smaller-scale the repititions also occurred because of the same
% reasons. Since these repitions disrupt the balanced representation of the
% trials in the data pool, they need to be marked and excluded from the
% final analysis.
% the same trial should not be repeated more than twice. To identify the
% repitions >2, the Postion index is used

% create a new varibale by putting together the necessary variables that
% are required to specify and mark the mR-seq, they are: 
% . TrialList(:,1) -> trialID 
% . TrialList(:,41) -> rewardDuration 
% . TrialList(:,3) -> PositionIndex (Check out the end of this script)
ImpVars = horzcat(TrialList(:,1), TrialList(:,41), TrialList(:,3));

repeat = zeros(size(ImpVars,1),1);
invalidRepeats = zeros(size(ImpVars,1),1);
if size(lastT,1) == 1
    if lastT < length(repeat)
        invalidRepeats(lastT+1:end) = 2;
    end
    for elementi = 2:lastT(1)
        posIdx1 = ImpVars(elementi-1, 3);
        posIdx2 = ImpVars(elementi, 3);
        if posIdx1 == posIdx2
           % if the PositionIndices of the trial_i = trial_{i-1},
           % trial_i can be a repeated trial. Mark it for now.
            repeat(elementi) = 1;
            if repeat(elementi) == repeat(elementi-1)
               % if the trial_i and trial_{i-1} are both marked, it
               % means that the same PositionIndex is repeated more
               % than twice because the mark is placed to all trials
               % of the same PositionIndex except the first one. In
               % other words, if the repitions is only twice, the first
               % trial is not marked and the second one is which means
               % that the current conditional statement that they share
               % the same marks will not be met.
                invalidRepeats(elementi-1) = 2;
            end
        else
            continue;
        end
    end
else
    if lastT(3) < length(repeat)
        invalidRepeats(lastT(1)+1:lastT(2)) = 2;
        invalidRepeats(lastT(3)+1:end) = 2;
    end
    loopStarts = [2, lastT(2)+1];
    loopEnds = [lastT(1), lastT(3)];
    for m = 1:2
        loopEnd = loopEnds(m);
        loopStart = loopStarts(m);
          for elementi = loopStart:loopEnd
            posIdx1 = ImpVars(elementi-1, 3);
            posIdx2 = ImpVars(elementi, 3);
            if posIdx1 == posIdx2
               % if the PositionIndices of the trial_i = trial_{i-1},
               % trial_i can be a repeated trial. Mark it for now.
                repeat(elementi) = 1;
                if repeat(elementi) == repeat(elementi-1)
                   % if the trial_i and trial_{i-1} are both marked, it
                   % means that the same PositionIndex is repeated more
                   % than twice because the mark is placed to all trials
                   % of the same PositionIndex except the first one. In
                   % other words, if the repitions is only twice, the first
                   % trial is not marked and the second one is which means
                   % that the current conditional statement that they share
                   % the same marks will not be met.
                    invalidRepeats(elementi-1) = 2;
                end
            else
                continue;
            end
         end
    end
end

%% find the beginning and the end of the microrepititions
% the beginning is marked with value "1" and the end is marked by "3".
% value "2" indicates the trials that are repeated and need to be
% discarded.
% Finally, value "0" are non-repititive trials.

% invalidRepeats = horzcat(invalidRepeats, invalidRepeats);

for i = 2: size(invalidRepeats,1)
    if invalidRepeats(i,1) ~= invalidRepeats(i-1,1)
        if invalidRepeats(i-1,1) == 0
            invalidRepeats(i-1,1) = 1;
        elseif invalidRepeats(i-1,1) == 2
            invalidRepeats(i,1) = 3;
        end
    end
end

repititions = invalidRepeats;
end

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Position: Left (135 deg) (X= -7.07; Y= 7.07)              Position: Right (45 deg) (X= 7.07; Y= 7.07)         
%           |IN (-30%)  | - |OUT (-30%) |                      |IN (-30%)  | - |OUT (-30%) | 
%LOW reward |   6       | 8 |   10      |           LOW reward |   0       | 2 |    4      |    
%HIGH reward|   7       | 9 |   11      |           HIGH reward|   1       | 3 |    5      | 
%
% High reward codes:    1,3,5,7,9,11	<odd>
% Low reward codes:     0,2,4,6,8,10	<even>
%
% Right-side codes:     0,1,2,3,4,5     <=5
% Left-side codes:      6,7,8,9,10,11   >5
%
% Stay-put codes:       2,3,8,9
% Inward ISS codes:     0,1,6,7
% outward ISS codes:    4,5,10,11