function tablePS = tablize_array(Arr, Arr_name, no_cols)

% This function converts the array to a table and assign column names  
% to make arrays readable.
% 
%
% Available tables:
%     . Psession, "Psession", 33 OR 34
%     . TrialList, "TrialList", 51
%
% input arguments:
%     . a < 2D array> with columns defined as the IDs or Kinematics variables of 
%     analysed eye movment data and the rows each from one trial.
%
%     . The array name
% 
%     . <number of columns> of the array as the input arguments. This is just to 
%     later ensure that the input array has the correct number of columns, cause 
%     the number of columns changes as the analysis develops. 
%
% Eample:
% >> tablize_array(TrialList, "TrialList", 51)
% 
% returns a table containing an appropriate name for each column.
    file_Details = struct('Arr_name', ...
            {"Psession", ...
            "TrialList"},...
            'col_Heads', ...
            {{'TrialNo', 'TrialID', ...
            'BlockNo', 'PositionIndex', 'TargetAppearTime', 'StimulationTime', ...
            'RewardDuration', 'RewardLevel_R2', 'TrialDir_R1', ...
            'Trialstep_correct_P1_O2', 'targetY_jump', 'targetX_jump', ...
            'targetX_jump2', 'Start', 'End', 'amp', 'amp50', 'VisErr', ...
            'RT', 'MovDur', 'PVindex_Fil_1st', 'PVindex_Fil_Hi', ...
            'PVindex_Unfil_1st', 'PVindex_Unfil_Hi', 'MaxVel_Fil_1st', ...
            'MaxVel_Fil_Hi', 'MaxVel_Unfil_1st', 'MaxVel_Unfil_Hi', ...
            'MaxVel_Norm_Fil_1st', 'MaxVel_Norm_Fil_Hi', ...
            'MaxVel_Norm_Unfil_1st', 'MaxVel_Norm_Unfil_Hi',...
            'VelidTrials_1', 'ValidTrialCounter'}, ...
            {'TrialNo0', 'SampleNo', 'Poolnumber', 'ValidTrials_1', ...
            'Timelimit', 'CorrectTrial_0', 'CorrectTrial_02', ...
            'Timelimit2', 'X1', 'X2_10', 'TrialID', 'EndX', 'EndY', ...
            'StartX', 'StartY', 'PositionIndex', 'TargetCounterOffset', ...
            'FixFail', 'DirectionOffsetIndex', 'DirectionOffset', ...
            'TargetAppearTime', 'RewardLevel', 'CurrentColorChangeTime2', ...
            'WasRewardGiven', 'GapStartTime', 'StimulationTime', ...
            'StartPointFromListX', 'StartPointFromListY',...
            'EndPointFromListX', 'EndPointFromListY', ...
            'MaximumVelocityMeasured', 'VelocityThreshold', ...
            'WasOverThreshold', 'WasFeedbackTrial', 'WasFreeChoiceTrial', ...
            'WasTimeout', 'CategoryChosen', 'IndexOfSecondTarget', ...
            'SecondTargetX', 'SecondTargetY', 'RewardDuration', 'ITI', ...
            'JumpTime', 'NoValidTrial', 'SecondFixFail', ...
            'DetectWinDurationFromList', 'WasTooLate', 'TrialID2', ...
            'TrialDir', 'TrialStep_crct', 'BlockNo'}});
    if ~exist('Arr_name', 'var') && ~exist('no_cols', 'var')
        disp('Error: please specify a **Arr**ay name and a **number of columns** and recall the function');
    elseif (Arr_name == file_Details(1).Arr_name)
        tablePS = array2table(Arr);
        tablePS.Properties.VariableNames = file_Details(1).col_Heads(1:no_cols);
%         assignin('base', 'tablePS', tablePS);
    elseif (Arr_name == file_Details(2).Arr_name)
        tablePS = array2table(Arr);
        tablePS.Properties.VariableNames = file_Details(2).col_Heads(1:no_cols);
%         assignin('base', 'tableTrialList', tableTrialList);
    end
 end