%% pool data across sessoions
%% find relevant mat files
% once this is done once, the output is stored and the next time the stored
% output is going to be used instead.

% find
% directory_main = 'J:\Monkey Project\Analysis\Data\Kruemmel\Analyzed';
% fileInfo = dir([directory_main, '\**\*.final.mat']);
% fileInfo(32:end,:) = [];

% store
% listfilename = 'listoffinaldatafiles_temp.mat';
% listfilepath = 'J:\Monkey Project\Analysis\Data\Kruemmel\Analyzed';
% save(fullfile(listfilepath, listfilename), 'file');
%% Load the list of MAT files
listfilename = 'listoffinaldatafiles_temp.mat';
listfilepath = 'J:\Monkey Project\Analysis\Data\Kruemmel\Analyzed';
load(fullfile(listfilepath, listfilename));
fileInfo = file;
clearvars listfilename listfilepath file;

%% pool

%initialize the data frame
df = [];
for i = 1:size(fileInfo, 1)
    disp(i);
    clearvars -except df i fileInfo name;
    
    % load
    load(fullfile(fileInfo(i).folder,fileInfo(i).name), 'session');
    
    % create new variables
    session_no = repmat(i, size(session.TrialList,1),1);
    sessionID = repmat(str2num(fileInfo(i).name(1:8)), size(session.TrialList,1),1);
    if contains( fileInfo(i).name, '_2')
        additionalID = repmat(2, size(session.TrialList,1),1);
    else
        additionalID = repmat(1, size(session.TrialList,1),1);
    end
    
    % organize the main varibales
    % the function "sessionData" also make some changes in the variables
    [trialID, block, validTrial, direction, reward, ISS, freeChoice,...
    addSac, addSacType, RT_p, amplitude_p, PV_p, duration_p, ...
    amplitudeOffset, amplitudeOffset50, ISI, TSI,...
    amplitude_c, PV_c, duration_c, errorX1, errorSize1, errorX2, ...
    errorSize2, ierrorX, ierrorSize, errorX1_50, errorX1_50Avg, ...
    ierrorX_50, ierrorX_50Avg, repititive] ...
    = sessionData(session);

    % concatenate variable to form the raw data frame
    df_temp = horzcat(session_no, ...
                sessionID, ...
                additionalID, ...
                trialID, ...
                block, ...
                validTrial, ...
                repititive, ...
                direction, ...
                reward, ...
                ISS,...
                freeChoice,...
                addSac, ...
                RT_p, ...
                amplitude_p, ...
                PV_p, ...
                duration_p, ...
                amplitudeOffset, ...
                amplitudeOffset50, ...
                ISI, ...
                TSI, ...
                amplitude_c, ...
                PV_c, ...
                duration_c, ...
                errorX1, ...
                errorSize1, ...
                errorX2, ...
                errorSize2, ...
                ierrorX, ...
                ierrorSize, ...
                errorX1_50, ...
                errorX1_50Avg, ...
                ierrorX_50, ...
                ierrorX_50Avg);
            
    % concatenate the new session data to the pooled data across the
    % previous sessions
    df = vertcat(df, df_temp);
end

%% convert df to table
df = array2table(df);
varNames = {'session_no'; 'sessionID'; 'additionalID'; 'trialID'; 'block'; ...
            'validTrial'; 'repititive'; 'direction'; 'reward'; 'ISS'; 'freeChoice'; ...
            'addSac'; 'RT_p'; 'amplitude_p'; 'PV_p'; ...
            'duration_p'; 'amplitudeOffset'; 'amplitudeOffset50'; ...
            'ISI'; 'TSI'; 'amplitude_c'; 'PV_c'; 'duration_c'; ...
            'errorX1'; 'errorSize1'; 'errorX2'; 'errorSize2'; 'ierrorX'; ...
            'ierrorSize'; 'errorX1_50'; 'errorX1_50Avg'; 'ierrorX_50'; ...
            'ierrorX_50Avg'};
df.Properties.VariableNames = varNames;
%% store the output as MAT file
storingPath = 'J:\Monkey Project\Analysis\Data\Kruemmel\Analyzed\Pooled';
storingName = 'df.mat';
save(fullfile(storingPath, storingName), 'df');

%% store as .CSV file format
storingPath = 'J:\Monkey Project\Analysis\Data\Kruemmel\Analyzed\Pooled';
storingName = 'df.csv';
writetable(df, fullfile(storingPath, storingName), ...
    'WriteVariableNames', true);
$$